SELECT 
    *
FROM
    sales_analysis.apple_global_sales_dataset;


 /** WHAT IS THE TOTAL REVENUE(USD) GENERATED FROM ALL SALES? **/
 
SELECT 
    SUM(revenue_usd) AS total_revenue
FROM
    apple_global_sales_dataset;
    
 
 /** HOW MANY TOTAL UNITS WERE SOLD ACROSS ALL PRODUCTS? **/
 
SELECT 
    SUM(units_sold) AS total_units_sold
FROM
    apple_global_sales_dataset;
 
 
 /** HOW MANY SALES TRANSACTIONS OCCURRED IN THE DATASET? **/
 
SELECT 
    COUNT(*) AS total_sales_transactions
FROM
    apple_global_sales_dataset;
    
 
 /** WHAT ARE THE DISTINCT PRODUCT CATEGORIES AVAILABLE? **/
 
SELECT DISTINCT
    product_category
FROM
    apple_global_sales_dataset;
    
 
 /** WHAT IS THE AVERAGE UNIT PRICE(USD) OF APPLE PRODUCTS? **/
 
SELECT 
    AVG(unit_price_usd) AS average_price
FROM
    apple_global_sales_dataset;
    
 
 /** WHAT ARE THE TOP 5 CITIES WITH THE HIGHEST REVENUE(USD)? **/
 
SELECT 
    city, SUM(revenue_usd) AS total_revenue
FROM
    apple_global_sales_dataset
GROUP BY city
ORDER BY total_revenue DESC
LIMIT 5;

 
/** WHICH COUNTRIES GENERATE THE MOST REVENUE(USD)? **/
 
SELECT 
    country, SUM(revenue_usd) AS total_revenue
FROM
    apple_global_sales_dataset
GROUP BY country
ORDER BY total_revenue DESC;
 
 
/** WHAT IS THE TOTAL REVENUE(USD) GENERATED BY EACH PRODUCT CATEGORY? **/
 
SELECT 
    product_category, SUM(revenue_usd) AS total_revenue
FROM
    apple_global_sales_dataset
GROUP BY product_category
ORDER BY total_revenue DESC;

  
/** WHICH PRODUCTS GENERATED THE HIGHEST REVENUE(USD)? **/
  
SELECT 
    product_name, SUM(revenue_usd) AS total_revenue
FROM
    apple_global_sales_dataset
GROUP BY product_name
ORDER BY total_revenue DESC
LIMIT 10;


/** WHAT IS THE AVERAGE CUSTOMER RATING FROM EACH PRODUCT? **/
   
SELECT 
    product_name, AVG(customer_rating) AS avg_rating
FROM
    apple_global_sales_dataset
GROUP BY product_name
ORDER BY avg_rating DESC;
    
    
/** WHAT IS THE TOTAL REVENUE(USD) GENERATED BY EACH SALES CHANNEL? **/
    
SELECT 
    sales_channel, SUM(revenue_usd) AS total_revenue
FROM
    apple_global_sales_dataset
GROUP BY sales_channel
ORDER BY total_revenue DESC;
     
     
/** WHICH PAYMENT METHOD IS USED THE MOST? **/
     
SELECT 
    payment_method, COUNT(*) AS total_transactions
FROM
    apple_global_sales_dataset
GROUP BY payment_method
ORDER BY total_transactions DESC;
      
      
/** WHAT IS THE REVENUE(USD) GENERATED EACH YEAR? **/
      
SELECT 
    sale_year, SUM(revenue_usd) AS yearly_revenue
FROM
    apple_global_sales_dataset
GROUP BY sale_year
ORDER BY sale_year;
       

/** WHAT IS THE MONTHLY SALES REVENUE(USD) TREND? **/
       
SELECT 
    sale_month, SUM(revenue_usd) AS monthly_revenue
FROM
    apple_global_sales_dataset
GROUP BY sale_month
ORDER BY monthly_revenue DESC;
        
        
/** WHAT ARE THE TOP 5 PRODUCTS BY UNITS SOLD? **/
        
SELECT 
    product_name, SUM(units_sold) AS total_units
FROM
    apple_global_sales_dataset
GROUP BY product_name
ORDER BY total_units DESC
LIMIT 5;
         

/** WHICH REGIONS HAVE THE HIGHEST AVERAGE REVENUE(USD) PER SALE? **/
         
SELECT 
    region, AVG(revenue_usd) AS avg_revenue
FROM
    apple_global_sales_dataset
GROUP BY region
ORDER BY avg_revenue DESC;


/** WHAT PERCENTAGE OF TOTAL REVENUE(USD) COMES FROM EACH PRODUCT CATEGORY? **/

SELECT 
    product_category,
    SUM(revenue_usd) AS category_revenue,
    ROUND(SUM(revenue_usd) * 100 / (SELECT 
                    SUM(revenue_usd)
                FROM
                    apple_global_sales_dataset),
            2) AS revenue_percentage
FROM
    apple_global_sales_dataset
GROUP BY product_category
ORDER BY revenue_percentage DESC;

 
/** WHICH CUSTOMER SEGMENT GENERATES THE MOST REVENUE(USD)? **/
 
SELECT 
    customer_segment, SUM(revenue_usd) AS total_revenue
FROM
    apple_global_sales_dataset
GROUP BY customer_segment
ORDER BY total_revenue DESC;
  

/** WHICH PRODUCTS HAVE THE HIGHEST RETURN RATE? **/
  
SELECT 
    product_name, COUNT(*) AS total_revenue
FROM
    apple_global_sales_dataset
WHERE
    return_status = ' Returned'
GROUP BY product_name
ORDER BY total_revenue DESC;

/** RANK PRODUCTS BASED ON TOTAL REVENUE(USD) GENERATED? **/

select product_name,
 sum(revenue_usd) as total_revenue,
 rank() over(order by sum(revenue_usd) desc) as revenue_rank
 from apple_global_sales_dataset
 group by product_name;
 

/** RANK CITIES BY REVENUE WITHIN EACH COUNTRY? **/
 
 select
  country,
  city,
  sum(revenue_usd) as total_revenue,
  rank() over( partition by country order by sum(revenue_usd)desc) as city_rank
  from apple_global_sales_dataset
  group by country,city;
  
  
/** FIND TOP 5 REVENUE GENERATING PRODUCTS? **/
 
 with product_revenue as (
  select
   product_name,
   sum(revenue_usd) as total_revenue
   from apple_global_sales_dataset
   group by product_name
   )
   select* from product_revenue
   order by total_revenue desc
   limit 5;
   
   
 
 